FROM hello-world

ARG APP_NAME
ARG APP_VERSION

LABEL version "${APP_VERSION}"
LABEL service "${APP_NAME}"
LABEL vendor "EmbeddedEnterprises"
LABEL product "robµlab"
LABEL maintainers "Fin Christensen <fchristensen@embedded.enterprises>"
